name: minecraft-website
services:
- build_command: yarn build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: Benwyw/minecraft-website
  name: minecraft-website
